from pathlib import Path
from html import escape
import json,re
root=Path(__file__).parent/'dist'
tr=['Hayatımın büyük kısmı merak etmekle geçti. Bir şeyin nasıl çalıştığını anlamak, bozulanı düzeltmek, yeni bir çözüm bulmak hep hoşuma gitti. Belki bu yüzden mühendis oldum; belki de mühendis olduğum için hâlâ her şeyi kurcalıyorum.', 'Günlerimin bir tarafında savunma sanayi, projeler, çözülmeyi bekleyen problemler ve en zoru insanlar var :) Öteki tarafında ise şarkılar…', 'Türk Sanat Müziği ve Türk Halk Müziği korolarında solist ve korist olarak şarkı söylüyorum. İkisi birbirinden uzak görünse de bana pek öyle gelmiyor; çünkü ne bir işi hakkıyla yapmak ne de bir şarkıyı gerçekten söylemek, sevmeden mümkün. İkisi de önce sevgi, sonra gayret, en sonunda biraz da yürek gerektiriyor.', 'Bu siteyi kendimi uzun uzun anlatmak için değil, yol boyunca ilgimi çeken şeylerden bana dair küçük izler bırakmak için hazırladım. Çünkü,']
en=['Curiosity has shaped much of my life. I’ve always enjoyed figuring out how things work, fixing what’s broken and finding a new way forward. Perhaps that’s why I became an engineer—or perhaps being an engineer is why I still can’t leave things unexplored.', 'One part of my day belongs to the defence industry: projects, problems waiting to be solved and, trickiest of all, people :) The other belongs to songs…', 'I sing both as a soloist and as a member of choirs devoted to Turkish classical and folk music. Engineering and music may seem worlds apart, but they’ve never felt that way to me. You can’t do a job with real care, or truly give voice to a song, unless your heart is in it. Both begin with love, ask for dedication and, in the end, take a little courage.', 'I made this site to leave a few traces of myself in the things that catch my attention along the way, rather than tell my whole life story. After all,']
de=['Die Neugier begleitet mich schon mein Leben lang. Ich habe immer gern herausgefunden, wie etwas funktioniert, Kaputtes repariert und nach neuen Lösungen gesucht. Vielleicht bin ich deshalb Ingenieur geworden. Vielleicht lässt mich aber auch gerade der Ingenieur in mir bis heute an allem tüfteln.', 'Die eine Seite meines Alltags besteht aus der Verteidigungsindustrie, Projekten, ungelösten Problemen und der wohl kniffligsten Aufgabe: dem Umgang mit Menschen :) Auf der anderen Seite ist die Musik …', 'Ich singe als Solist und im Chor, in der klassischen türkischen Musik ebenso wie in der türkischen Volksmusik. Ingenieurwesen und Musik scheinen weit auseinanderzuliegen. Für mich liegen sie jedoch nah beieinander: Weder kann man seine Arbeit mit Hingabe tun noch ein Lied wirklich zum Klingen bringen, wenn man nicht mit dem Herzen dabei ist. Beides braucht zuerst Liebe, dann Ausdauer und am Ende auch ein wenig Mut.', 'Diese Seite soll keine ausführliche Lebensgeschichte sein. Ich möchte hier kleine Spuren von mir hinterlassen – in den Dingen, die mich unterwegs berühren und neugierig machen. Denn:']
content={
 'tr':dict(heading='Hakkımda',role='Electronics Engineer',title='Elektronik Mühendisi & Proje Yöneticisi',p=tr,quote='“Ömür çiçek kadar narin, bir gün kadar kısa.”',email='Email',desc='Burak Akgül, Hacettepe Üniversitesi Elektrik-Elektronik Mühendisliği mezunu ve ASELSAN’da proje yöneticisidir. Türk Sanat Müziği ve Türk Halk Müziği korolarında solist olarak yer almaktadır.'),
 'en':dict(heading='About me',role='Electronics Engineer',title='Electronics Engineer & Project Manager',p=en,quote='“Life is as delicate as a flower, as fleeting as a day.”',email='Email',desc='Burak Akgül is an electronics engineer, a Hacettepe University graduate and a project manager at ASELSAN. He also sings Turkish classical and folk music.'),
 'de':dict(heading='Über mich',role='Elektronikingenieur',title='Elektronikingenieur & Projektmanager',p=de,quote='„Das Leben ist zart wie eine Blüte, flüchtig wie ein Tag.“',email='E-Mail',desc='Burak Akgül ist Elektronikingenieur, Absolvent der Hacettepe-Universität und Projektmanager bei ASELSAN. Außerdem singt er klassische türkische Musik und türkische Volksmusik.')}
links=[('YouTube','https://www.youtube.com/@bburakakgul','youtube'),('Instagram','https://instagram.com/buraknakgul','instagram'),('LinkedIn','https://www.linkedin.com/in/burak-akgül-1805a34a/','linkedin'),('X','https://x.com/bburakakgul','x'),('Spotify','https://open.spotify.com/playlist/0z52J8u9gif9GPx07TuLBV?si=e40f9613562a4ded','spotify'),('Email','mailto:buraknazif@gmail.com','email')]
icons={'youtube':'<rect x="3" y="6" width="26" height="20" rx="6" fill="currentColor"/><path d="m13 11 9 5-9 5z" fill="#ab2626"/>','instagram':'<rect x="5" y="5" width="22" height="22" rx="6"/><circle cx="16" cy="16" r="5"/><circle cx="23" cy="9" r="1" fill="currentColor"/>','linkedin':'<text x="4" y="25" fill="currentColor" stroke="none" font-family="Arial" font-weight="bold" font-size="26">in</text>','x':'<path d="M6 5h6l14 22h-6zM25 5 7 27"/>','spotify':'<circle cx="16" cy="16" r="13" fill="currentColor"/><g stroke="#1ed760"><path d="M8 12q8-4 16 1M9 17q7-3 14 1M11 22q5-2 10 0"/></g>','email':'<rect x="3" y="6" width="26" height="20" rx="2"/><path d="m3 8 13 10L29 8"/>'}
tr[2:3]=tr[2].split('. ',2)
tr[2]+='.'
tr[3]+='.'
en[2:3]=[en[2].split(' Engineering')[0], 'Engineering'+en[2].split(' Engineering')[1].split(' Both')[0], 'Both'+en[2].split(' Both')[1]]
de[2:3]=[de[2].split(' Ingenieurwesen')[0], 'Ingenieurwesen'+de[2].split(' Ingenieurwesen')[1].split(' Beides')[0], 'Beides'+de[2].split(' Beides')[1]]
paths={'tr':'/','en':'/en/','de':'/de/'}
labels={'tr':'Türkçe','en':'English','de':'Deutsch'}
schemas=json.loads((Path(__file__).parent/'profile.json').read_text())

for lang,c in content.items():
 url='https://burakakgul.com'+paths[lang]
 page_schemas=json.loads(json.dumps(schemas))
 page_schemas[0]['url']=url
 page_schemas[0]['@id']=url+'#profile'
 page_schemas[0]['inLanguage']=lang
 nav=''.join(f'<a href="{paths[l]}" lang="{l}" hreflang="{l}" title="{labels[l]}" aria-label="{labels[l]}"'+(' aria-current="page"' if l==lang else '')+f'>{l.upper()}</a>' for l in content)
 social=''.join(f'<li><a class="social {key}" href="{escape(href)}" data-social="{name}"><span>{c["email"] if key=="email" else name}</span><svg aria-hidden="true" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">{icons[key]}</svg></a></li>' for name,href,key in links)
 page=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Burak Akgül | {c['title']}</title><meta name="description" content="{escape(c['desc'])}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#FDEBEB"><link rel="icon" href="/favicon.gif" type="image/gif"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="canonical" href="{url}">
{''.join(f'<link rel="alternate" hreflang="{l}" href="https://burakakgul.com{p}">' for l,p in paths.items())}<link rel="alternate" hreflang="x-default" href="https://burakakgul.com/">
<meta property="og:type" content="website"><meta property="og:site_name" content="Burak Akgül"><meta property="og:title" content="Burak Akgül | {c['title']}"><meta property="og:description" content="{escape(c['desc'])}"><meta property="og:url" content="{url}"><meta property="og:locale" content="{dict(tr='tr_TR',en='en_GB',de='de_DE')[lang]}"><meta property="og:image" content="https://burakakgul.com/assets/social-preview.png"><meta property="og:image:alt" content="Burak Akgül"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Burak Akgül | {c['title']}"><meta name="twitter:description" content="{escape(c['desc'])}"><meta name="twitter:image" content="https://burakakgul.com/assets/social-preview.png">
<link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script>
{''.join('<script type="application/ld+json">'+json.dumps(s,ensure_ascii=False)+'</script>' for s in page_schemas)}</head>
<body><div class="portrait" role="img" aria-label="Burak Akgül"></div><main><section class="intro pattern" aria-label="Burak Akgül"><div class="intro-inner"><nav class="languages" aria-label="{dict(tr='Dil seçimi',en='Language',de='Sprache')[lang]}">{nav}</nav><h1>Burak Akgül</h1><p class="profession">{c['role']}</p><div class="zigzag" aria-hidden="true"></div><ul class="socials">{social}</ul><p class="copyright">Copyright © 2026<br>Burak Akgül</p></div></section><div class="zigzag about-divider" aria-hidden="true"></div><section class="about pattern" id="hakkimda"><div class="about-inner"><h2>{c['heading']}</h2>{''.join('<p>'+escape(p)+'</p>' for p in c['p'])}<p class="quote">{c['quote']}</p></div></section></main></body></html>'''
 target=root/paths[lang].strip('/')/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(page)
(root/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://burakakgul.com/sitemap.xml\n')

(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+''.join('<url><loc>https://burakakgul.com'+path+'</loc>'+''.join('<xhtml:link rel="alternate" hreflang="'+lang+'" href="https://burakakgul.com'+target+'"/>' for lang,target in {**paths,'x-default':'/'}.items())+'</url>' for path in paths.values())+'</urlset>\n')