from pathlib import Path
from html import escape
import json,re
root=Path(__file__).parent/'dist'
tr=['Hayatımın büyük kısmı merak etmekle geçti. Bir şeyin nasıl çalıştığını anlamak, bozulanı düzeltmek, yeni bir çözüm bulmak hep hoşuma gitti. Belki bu yüzden mühendis oldum; belki de mühendis olduğum için hâlâ her şeyi kurcalıyorum.', 'Günlerimin bir tarafında savunma sanayi, projeler, çözülmeyi bekleyen problemler ve en zoru insanlar var :) Öteki tarafında ise şarkılar…', 'Türk Sanat Müziği ve Türk Halk Müziği korolarında solist ve korist olarak şarkı söylüyorum. İkisi birbirinden uzak görünse de bana pek öyle gelmiyor; çünkü ne bir işi hakkıyla yapmak ne de bir şarkıyı gerçekten söylemek, sevmeden mümkün. İkisi de önce sevgi, sonra gayret, en sonunda biraz da yürek gerektiriyor.', 'Bu siteyi kendimi uzun uzun anlatmak için değil, yol boyunca ilgimi çeken şeylerden bana dair küçük izler bırakmak için hazırladım. Çünkü,']
en=['I’ve always been curious. I like understanding how things work, fixing things and finding new solutions. Maybe that’s why I became an engineer. Or maybe being an engineer is why I still like to tinker with everything.', 'Part of my day is about the defence industry, projects, problems to solve and, the hardest part, people :) The other part is about songs…', 'I sing Turkish classical and folk music, both as a soloist and in choirs.', 'They may seem very different from engineering, but I don’t really see it that way. I think you need to love what you do, whether it’s your work or a song.', 'Both take love, effort and a little courage.', 'I made this site to share a few things that interest me along the way. Just small pieces of my life, rather than a long story about myself. Because,']
de=['Ich war schon immer neugierig. Ich verstehe gern, wie Dinge funktionieren, repariere etwas und suche nach neuen Lösungen. Vielleicht bin ich deshalb Ingenieur geworden. Oder vielleicht probiere ich gerade deshalb immer noch so gern alles aus.', 'Ein Teil meines Alltags dreht sich um die Verteidigungsindustrie, Projekte, Probleme und das Schwierigste: Menschen :) Im anderen Teil geht es um Musik…', 'Ich singe klassische türkische Musik und türkische Volksmusik, als Solist und im Chor.', 'Das klingt vielleicht ganz anders als mein Beruf. Für mich passt es aber gut zusammen. Ob bei der Arbeit oder beim Singen: Man muss mögen, was man tut.', 'Beides braucht Liebe, Mühe und ein bisschen Mut.', 'Auf dieser Seite möchte ich ein paar Dinge teilen, die mich unterwegs interessieren. Kleine Einblicke in mein Leben, statt einer langen Geschichte über mich. Denn:']
content={
 'tr':dict(heading='Hakkımda',role='Elektronik Mühendisi',title='Elektronik Mühendisi & Proje Yöneticisi',p=tr,quote='“Ömür çiçek kadar narin, bir gün kadar kısa.”',email='E-Posta',desc='Burak Akgül, Hacettepe Üniversitesi Elektrik-Elektronik Mühendisliği mezunu ve proje yöneticisidir. Türk Sanat Müziği ve Türk Halk Müziği korolarında solist olarak yer almaktadır.'),
 'en':dict(heading='About me',role='Electronics Engineer',title='Electronics Engineer & Project Manager',p=en,quote='“Life is as delicate as a flower, as fleeting as a day.”',email='E-Mail',desc='Burak Akgül is an electronics engineer, a Hacettepe University graduate and a project manager. He also sings Turkish classical and folk music.'),
 'de':dict(heading='Über mich',role='Elektronikingenieur',title='Elektronikingenieur & Projektmanager',p=de,quote='„Das Leben ist zart wie eine Blüte, flüchtig wie ein Tag.“',email='E-Mail',desc='Burak Akgül ist Elektronikingenieur, Absolvent der Hacettepe-Universität und Projektmanager. Außerdem singt er klassische türkische Musik und türkische Volksmusik.')}
links=[('YouTube','https://www.youtube.com/@bburakakgul','youtube'),('Instagram','https://instagram.com/buraknakgul','instagram'),('LinkedIn','https://www.linkedin.com/in/burak-akgül-1805a34a/','linkedin'),('X','https://x.com/bburakakgul','x'),('Spotify','https://open.spotify.com/playlist/0z52J8u9gif9GPx07TuLBV?si=e40f9613562a4ded','spotify'),('Email','mailto:buraknazif@gmail.com','email')]
icons={'youtube':'<rect x="3" y="6" width="26" height="20" rx="6" fill="currentColor"/><path d="m13 11 9 5-9 5z" fill="#ab2626"/>','instagram':'<rect x="5" y="5" width="22" height="22" rx="6"/><circle cx="16" cy="16" r="5"/><circle cx="23" cy="9" r="1" fill="currentColor"/>','linkedin':'<text x="4" y="25" fill="currentColor" stroke="none" font-family="Arial" font-weight="bold" font-size="26">in</text>','x':'<path d="M6 5h6l14 22h-6zM25 5 7 27"/>','spotify':'<circle cx="16" cy="16" r="13" fill="currentColor"/><g stroke="#1ed760"><path d="M8 12q8-4 16 1M9 17q7-3 14 1M11 22q5-2 10 0"/></g>','email':'<rect x="3" y="6" width="26" height="20" rx="2"/><path d="m3 8 13 10L29 8"/>'}
tr[2:3]=tr[2].split('. ',2)
tr[2]+='.'
tr[3]+='.'
tr[-1]='Bu siteyi kendimi uzun uzun anlatmak için değil, bana dair küçük izler bırakmak için hazırladım. Çünkü,'
en[-1]='I made this site not to tell a long story about myself, but to leave a few small traces of who I am. Because,'
de[-1]='Ich habe diese Seite nicht gemacht, um lange über mich zu erzählen, sondern um ein paar kleine Spuren von mir zu hinterlassen. Denn:'
paths={'tr':'/','en':'/en/','de':'/de/'}
labels={'tr':'Türkçe','en':'English','de':'Deutsch'}
schemas=json.loads((Path(__file__).parent/'profile.json').read_text())

for lang,c in content.items():
 url='https://burakakgul.com'+paths[lang]
 page_schemas=json.loads(json.dumps(schemas))
 page_schemas[0]['url']=url
 page_schemas[0]['@id']=url+'#profile'
 page_schemas[0]['inLanguage']=lang
 nav=''.join(f'<a href="{paths[l]}" lang="{l}" hreflang="{l}" title="{labels[l]}" aria-label="{labels[l]}"'+(' aria-current="page"' if l==lang else '')+f'>{l.upper()}</a>' for l in content)
 social=''.join(f'<li><a class="social {key}" href="{escape(href)}" data-social="{name}"><span>{c["email"] if key=="email" else name}</span><svg aria-hidden="true" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">{icons[key]}</svg></a></li>' for name,href,key in links)
 page=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Burak Akgül | {c['title']}</title><meta name="description" content="{escape(c['desc'])}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#FDEBEB"><link rel="icon" href="/favicon.gif" type="image/gif"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="canonical" href="{url}">
{''.join(f'<link rel="alternate" hreflang="{l}" href="https://burakakgul.com{p}">' for l,p in paths.items())}<link rel="alternate" hreflang="x-default" href="https://burakakgul.com/">
<meta property="og:type" content="website"><meta property="og:site_name" content="Burak Akgül"><meta property="og:title" content="Burak Akgül | {c['title']}"><meta property="og:description" content="{escape(c['desc'])}"><meta property="og:url" content="{url}"><meta property="og:locale" content="{dict(tr='tr_TR',en='en_GB',de='de_DE')[lang]}"><meta property="og:image" content="https://burakakgul.com/assets/social-preview.png"><meta property="og:image:alt" content="Burak Akgül"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Burak Akgül | {c['title']}"><meta name="twitter:description" content="{escape(c['desc'])}"><meta name="twitter:image" content="https://burakakgul.com/assets/social-preview.png">
<link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script>
{''.join('<script type="application/ld+json">'+json.dumps(s,ensure_ascii=False)+'</script>' for s in page_schemas)}</head>
<body><div class="portrait" role="img" aria-label="Burak Akgül"></div><main><section class="intro pattern" aria-label="Burak Akgül"><div class="intro-inner"><nav class="languages" aria-label="{dict(tr='Dil seçimi',en='Language',de='Sprache')[lang]}">{nav}</nav><h1>Burak Akgül</h1><p class="profession">{c['role']}</p><div class="zigzag" aria-hidden="true"></div><ul class="socials">{social}</ul><p class="copyright">Copyright © 2026<br>Burak Akgül</p></div></section><div class="zigzag about-divider" aria-hidden="true"></div><section class="about pattern" id="hakkimda"><div class="about-inner"><h2>{c['heading']}</h2>{''.join('<p>'+escape(p).replace('ve en zoru insanlar var :)', '<span class="keep-together">ve en zoru insanlar var :)</span>')+'</p>' for p in c['p'])}<p class="quote">{c['quote']}</p></div></section></main></body></html>'''
 target=root/paths[lang].strip('/')/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(page)
(root/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://burakakgul.com/sitemap.xml\n')

(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+''.join('<url><loc>https://burakakgul.com'+path+'</loc>'+''.join('<xhtml:link rel="alternate" hreflang="'+lang+'" href="https://burakakgul.com'+target+'"/>' for lang,target in {**paths,'x-default':'/'}.items())+'</url>' for path in paths.values())+'</urlset>\n')
